// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_df8gZqH-wpBMXARV8u9LxLL3ZiDStM',
    appId: '1:531658192885:web:6c5abe2b4d9bfcdd3a12bc',
    messagingSenderId: '531658192885',
    projectId: 'kuliah-98fc7',
    authDomain: 'kuliah-98fc7.firebaseapp.com',
    storageBucket: 'kuliah-98fc7.firebasestorage.app',
    measurementId: 'G-E1GZB59029',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wnlzyCP1rcTqlUx0IcvZ7fnEirDd5WI',
    appId: '1:531658192885:android:371754a2e7d43cfa3a12bc',
    messagingSenderId: '531658192885',
    projectId: 'kuliah-98fc7',
    storageBucket: 'kuliah-98fc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAGADjYiVSCaJqgX5y-U3V1OkUqT2zfqA',
    appId: '1:531658192885:ios:b4c50361d78164fe3a12bc',
    messagingSenderId: '531658192885',
    projectId: 'kuliah-98fc7',
    storageBucket: 'kuliah-98fc7.firebasestorage.app',
    iosBundleId: 'com.example.biodata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAGADjYiVSCaJqgX5y-U3V1OkUqT2zfqA',
    appId: '1:531658192885:ios:b4c50361d78164fe3a12bc',
    messagingSenderId: '531658192885',
    projectId: 'kuliah-98fc7',
    storageBucket: 'kuliah-98fc7.firebasestorage.app',
    iosBundleId: 'com.example.biodata',
  );
}
